### ISSUE TITLE
No usar "nombres" sino objetos en los parámetros de métodos

### ISSUE THREAD

**Issue by maurociancio** [FrancoPandolfo/DNT#1]
https://github.com/FrancoPandolfo/DNT/blob/bb010e0befe29fc9733dca8a60251cd7f7fab817/grails-app/domain/organizadordeeventos/Evento.groovy#L39

Que no reciba un String sino un Proveedor, por ejemplo.

**Comment by FrancoPandolfo** [comment]
anotado

**Comment by FrancoPandolfo** [comment]
todo cambiado
