### ISSUE TITLE
Acá hay una doble relación entre usuarios y eventos (una con usuario y otra con administrador)

### ISSUE THREAD

**Issue by maurociancio** [FrancoPandolfo/DNT#11]
https://github.com/FrancoPandolfo/DNT/blob/edd3910ec9b04d683434ca9d139a42eb2c765f08/grails-app/domain/organizadordeeventos/Usuario.groovy#L25
Me hace ruido ese diseño.

**Comment by FrancoPandolfo** [comment]
saque a los usuarios y admins de evento
