### ISSUE TITLE
Dudoso un método sin parámetros que cree un proveedor nuevo

### ISSUE THREAD

**Issue by maurociancio** [FrancoPandolfo/DNT#2]
https://github.com/FrancoPandolfo/DNT/blob/bb010e0befe29fc9733dca8a60251cd7f7fab817/grails-app/domain/organizadordeeventos/Evento.groovy#L30

**Comment by FrancoPandolfo** [comment]
ya estan modificados los metodos. Usuario tiene proveedores que los puede agregar a un evento
