### ISSUE TITLE
esta estructura no creo que se pueda mapear. probablemente falte una entidad.

### ISSUE THREAD

**Issue by maurociancio** [FrancoPandolfo/DNT#4]
https://github.com/FrancoPandolfo/DNT/blob/bb010e0befe29fc9733dca8a60251cd7f7fab817/grails-app/domain/organizadordeeventos/Evento.groovy#L14

**Comment by FrancoPandolfo** [comment]
aaa que lastima no actualize el master, el ultimo push fue a la branch

**Comment by FrancoPandolfo** [comment]
infraestructura ya lo volamos, ahora es un Item mas que puede tener proveedor
