### ISSUE TITLE
No es muy comun usar un mapa adentro de una entidad. Suena a que falta una entidad que sea de relación.

### ISSUE THREAD

**Issue by maurociancio** [FrancoPandolfo/DNT#5]
https://github.com/FrancoPandolfo/DNT/blob/bb010e0befe29fc9733dca8a60251cd7f7fab817/grails-app/domain/organizadordeeventos/Proveedor.groovy#L8

**Comment by FrancoPandolfo** [comment]
compra ahora es un objeto llamado Item
