### ISSUE TITLE
Esta clase no es una entidad, no va acá. Va en src/groovy

### ISSUE THREAD

**Issue by maurociancio** [FrancoPandolfo/DNT#9]
https://github.com/FrancoPandolfo/DNT/blob/edd3910ec9b04d683434ca9d139a42eb2c765f08/grails-app/domain/organizadordeeventos/Dinero.groovy#L3

**Comment by FrancoPandolfo** [comment]
hecho, pero sale un Warning porque le deje el 
package organizadordeeventos
el tema que si se lo saco nose como importar Dinero en las otras clases

**Comment by FrancoPandolfo** [comment]
no me esta compilando por esa razon

**Comment by augusjoa** [comment]
Arreglado
https://github.com/FrancoPandolfo/DNT/blob/5dd60bf126848c466143948d4eca221ef466583b/src/main/groovy/organizadordeeventos/Dinero.groovy#L4
